#include "wave.hpp"

#include "../config/config_loader.hpp"
#include "../utils/process.hpp"

#include <CLI/CLI.hpp>
#include <csignal>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <unistd.h>
#include <vector>

namespace
{
    using namespace simforge::cli;

    struct WaveOptions
    {
        std::string tb_name;
        int period_ms = 500; // gtkwave repscript tick
        bool no_reload = false;
        bool foreground = false;
        bool restart = false;
    };

    std::string reload_script_body()
    {
        return R"TCL(# Auto-generated by simforge - regenerated on every 'simforge wave'. Do not edit.

set sf_dump [gtkwave::getDumpFileName]

if {[file exists $sf_dump]} {
    set sf_m [file mtime $sf_dump]
    set sf_s [file size $sf_dump]

    if {![info exists ::sf_prev_m]} {
        set ::sf_prev_m $sf_m
        set ::sf_prev_s $sf_s
        set ::sf_settled 1
    } elseif {$sf_m != $::sf_prev_m || $sf_s != $::sf_prev_s} {
        # still being written by the simulator - wait for it to stop changing
        set ::sf_prev_m $sf_m
        set ::sf_prev_s $sf_s
        set ::sf_settled 0
    } elseif {$::sf_settled == 0} {
        set ::sf_settled 1
        catch {gtkwave::reLoadFile}
    }
}

# persist the trace layout as soon as it changes, so closing the window doesn't lose it
set sf_sigs [gtkwave::getDisplayedSignals]
if {![info exists ::sf_prev_sigs]} {
    set ::sf_prev_sigs $sf_sigs
} elseif {$sf_sigs ne $::sf_prev_sigs} {
    set ::sf_prev_sigs $sf_sigs
    catch {gtkwave::/File/Write_Save_File}
}
)TCL";
    }

    std::filesystem::path find_wave_file(const std::filesystem::path &build_dir)
    {
        if (!std::filesystem::exists(build_dir))
            return {};

        std::filesystem::path newest;
        std::filesystem::file_time_type newest_time{};
        for (const auto &entry : std::filesystem::directory_iterator(build_dir))
        {
            const auto ext = entry.path().extension().string();
            if (ext != ".vcd" && ext != ".fst")
                continue;
            auto t = std::filesystem::last_write_time(entry.path());
            if (newest.empty() || t > newest_time)
            {
                newest = entry.path();
                newest_time = t;
            }
        }
        return newest;
    }

    pid_t read_pid_file(const std::filesystem::path &p)
    {
        std::ifstream f(p);
        if (!f)
            return -1;
        pid_t pid = -1;
        f >> pid;
        return pid;
    }

    void run(const WaveOptions &opts)
    {
        const auto root = std::filesystem::current_path();
        const auto cfg = ConfigLoader::load(root);
        const auto &tb = cfg.get_tb(opts.tb_name);

        const auto build_dir = root / cfg.paths.build / "tb" / tb.subdir();
        const auto wave_file = find_wave_file(build_dir);

        if (wave_file.empty())
            throw std::runtime_error("No waveform file found in " + build_dir.string() + "\nRun 'simforge run " + tb.subdir() + "' first.");

        if (utils::which("gtkwave").empty())
            throw std::runtime_error("gtkwave not found on PATH - install it first.");

        const auto save_file = root / cfg.paths.tb / tb.subdir() / (tb.name + ".gtkw");
        const auto pid_file = build_dir / ".gtkwave.pid";
        const auto script_file = build_dir / ".simforge_reload.tcl";
        const auto log_file = build_dir / "gtkwave.log";

        pid_t existing = read_pid_file(pid_file);
        if (utils::pid_alive(existing))
        {
            if (!opts.restart)
            {
                std::cout << "gtkwave is already open on '" << tb.subdir() << "' (pid " << existing << ").\n"
                          << "It reloads by itself after 'simforge run' - no need to reopen it.\n"
                          << "Use --restart to force a fresh instance.\n";
                return;
            }
            std::cout << "Stopping existing gtkwave (pid " << existing << ")...\n";
            kill(existing, SIGTERM);
            for (int i = 0; i < 20 && utils::pid_alive(existing); ++i)
                usleep(100000);
        }

        std::vector<std::string> args;

        if (!opts.no_reload)
        {
            std::filesystem::create_directories(build_dir);
            std::ofstream sf(script_file);
            if (!sf)
                throw std::runtime_error("Cannot write " + script_file.string());
            sf << reload_script_body();
            sf.close();

            args.push_back("-R");
            args.push_back(script_file.string());
            args.push_back("-P");
            args.push_back(std::to_string(opts.period_ms));
        }

        args.push_back("-a");
        args.push_back(save_file.string());
        args.push_back(wave_file.string());

        const bool have_layout = std::filesystem::exists(save_file);

        if (opts.foreground)
        {
            std::cout << "Opening " << wave_file.filename().string() << " in gtkwave (foreground)...\n";
            int rc = utils::run_interactive("gtkwave", args, root);
            if (rc != 0)
                throw std::runtime_error("gtkwave exited with code " + std::to_string(rc));
            return;
        }

        std::filesystem::create_directories(save_file.parent_path());
        pid_t pid = utils::run_detached("gtkwave", args, root, log_file);
        if (pid <= 0)
            throw std::runtime_error("Failed to launch gtkwave (see " + log_file.string() + ")");

        std::ofstream pf(pid_file);
        if (pf)
            pf << pid << "\n";

        std::cout << "gtkwave opened on " << wave_file.filename().string() << " (pid " << pid << ", detached).\n";
        std::cout
            << (have_layout ? "  Trace layout restored from " + save_file.filename().string() + "\n"
                            : "  No saved layout yet - the traces you add are saved to " + save_file.filename().string() + " automatically.\n");
        if (!opts.no_reload)
            std::cout << "  Leave it open: it reloads automatically after each 'simforge run'.\n";
    }
} // anonymous namespace

void register_wave_command(CLI::App &app)
{
    auto *cmd = app.add_subcommand("wave", "Open the latest waveform dump in GTKWave (detached, auto-reloading)");

    auto opts = std::make_shared<WaveOptions>();

    cmd->add_option("tb_name", opts->tb_name, "Testbench name (bare, or '<group>/<name>' to disambiguate)")->required();

    cmd->add_option("--period", opts->period_ms, "Auto-reload poll period in ms (default: 500)")->default_val(500);

    cmd->add_flag("--no-reload", opts->no_reload, "Don't watch the dump for changes (plain gtkwave)");

    cmd->add_flag("--fg", opts->foreground, "Run gtkwave in the foreground, holding the terminal");

    cmd->add_flag("--restart", opts->restart, "Close an already-running instance for this testbench and open a fresh one");

    cmd->callback([opts]() { run(*opts); });
}
