#include "cmake_gen.hpp"

#include <fstream>
#include <sstream>
#include <stdexcept>

namespace simforge::cli::utils
{
    void generate_tb_cmake(const simforge::cli::SimforgeConfig &cfg, const std::string &tb_name, const std::filesystem::path &project_root)
    {
        const auto &tb = cfg.get_tb(tb_name);
        const auto vc = cfg.effective_verilator(tb_name);

        const auto out_dir = project_root / cfg.paths.build / "tb" / tb_name;
        std::filesystem::create_directories(out_dir);
        const auto out_path = out_dir / "CMakeLists.txt";

        std::ofstream f(out_path);
        if (!f)
            throw std::runtime_error("Cannot write " + out_path.string());

        const auto abs_rtl = (project_root / cfg.paths.rtl).string();
        const auto abs_tb = (project_root / cfg.paths.tb / tb_name).string();
        const auto abs_build = out_dir.string();

        // DUT sv_top: wrapper if it exists, else raw RTL match
        std::string sv_wrapper = tb.resolved_sv_top((project_root / cfg.paths.tb).string());

        f << "# ================================================================\n"
          << "# Auto-generated by simforge - DO NOT EDIT\n"
          << "# Regenerate with: simforge build " << tb_name << "\n"
          << "# ================================================================\n\n"
          << "cmake_minimum_required(VERSION 3.22)\n\n"
          << "set(MODULE_NAME " << tb_name << ")\n"
          << "set(TOP_MODULE  " << tb.top << ")\n\n"
          << "project(${MODULE_NAME}_tb LANGUAGES CXX)\n\n"
          << "set(CMAKE_CXX_STANDARD 20)\n"
          << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n"
          << "add_subdirectory(\"" << (project_root / "libs/simforge").string() << "\" simforge)\n\n"
          << "find_package(VERILATOR REQUIRED)\n\n";

        // Package sources
        f << "# == SV Packages =================================================\n";
        for (const auto &pkg : cfg.paths.packages)
            f << "file(GLOB PKG_SV_" << pkg << " \"" << (project_root / pkg).string() << "/*.sv\")\n";

        f << "set(PKG_SV";
        for (const auto &pkg : cfg.paths.packages)
            f << " ${PKG_SV_" << pkg << "}";
        f << ")\n\n";

        // RTL sources
        f << "# == RTL sources ==================================================\n"
          << "file(GLOB_RECURSE RTL_SV_ALL \"" << abs_rtl << "/**/*.sv\")\n"
          << "list(REMOVE_ITEM RTL_SV_ALL ${PKG_SV})\n\n";

        // C++ sources
        f << "# == C++ sources =================================================\n"
          << "file(GLOB_RECURSE TB_SOURCES \"" << abs_tb << "/*.cpp\")\n\n"
          << "message(STATUS \"TB_SOURCES = ${TB_SOURCES}\")\n\n";

        // Executable
        f << "# == Testbench binary =============================================\n"
          << "add_executable(${MODULE_NAME}_tb ${TB_SOURCES})\n"
          << "target_link_libraries(${MODULE_NAME}_tb PRIVATE\n"
          << "    simforge::uvm\n"
          << "    simforge::backend::verilator\n"
          << ")\n\n";

        // verilate() call
        f << "# == Verilate =====================================================\n";

        // Determine SV top: use wrapper if it exists
        f << "set(SV_WRAPPER \"" << sv_wrapper << "\")\n"
          << "if(EXISTS ${SV_WRAPPER})\n"
          << "    set(SV_TOP ${SV_WRAPPER})\n"
          << "    set(VMOD   " << tb.top << ")\n"
          << "else()\n"
          << "    file(GLOB_RECURSE RTL_MATCH \"" << abs_rtl << "/**/" << tb.top << ".sv\")\n"
          << "    if(NOT RTL_MATCH)\n"
          << "        message(FATAL_ERROR \"No RTL found for module " << tb.top << "\")\n"
          << "    endif()\n"
          << "    list(GET RTL_MATCH 0 SV_TOP)\n"
          << "    set(VMOD " << tb.top << ")\n"
          << "endif()\n\n";

        // verilate() args
        bool trace = (cfg.artifacts.vcd || cfg.artifacts.fst) && vc.trace_level > 0;
        std::string trace_type = cfg.artifacts.fst ? "FST" : "VCD";

        f << "verilate(${MODULE_NAME}_tb\n"
          << "    SOURCES\n"
          << "        ${PKG_SV}\n"
          << "        ${RTL_SV_ALL}\n"
          << "        ${SV_TOP}\n"
          << "    TOP_MODULE ${VMOD}\n"
          << "    PREFIX     V${VMOD}\n";

        if (trace)
            f << "    TRACE_" << trace_type << " ON\n";

        // Global + local extra verilator args
        if (!vc.args.empty())
        {
            f << "    VERILATOR_ARGS";
            for (const auto &a : vc.args)
                f << " " << a;
            f << "\n";
        }

        // Include dirs
        f << "    INCLUDE_DIRS\n"
          << "        \"" << abs_rtl << "\"\n";
        for (const auto &d : vc.include_dirs)
            f << "        \"" << (project_root / d).string() << "\"\n";

        f << ")\n";
    }
} // namespace simforge::cli::utils
