#!/usr/bin/env python3

"""
embed_templates.py - invoked by CMake at build time.

Reads every *.in file under the templates/ directory and generates
templates_embed.hpp with one constexpr std::string_view per file,
organized in nested namespaces that mirror the directory structure.

Usage:
    python3 embed_templates.py <templates_dir> <output_header>
"""

import sys
import os
import re

def to_cpp_identifier(s: str) -> str:
    """Convert any string to a valid C++ identifier: dots, dashes, slashes -> underscore."""
    s = re.sub(r'[.\-/\\]', '_', s)
    return s

def strip_in(name: str) -> str:
    """Remove the trailing .in extension."""
    return name[:-3] if name.endswith('.in') else name

def collect(templates_dir: str):
    """Yield (rel_path_posix, abs_path) for every *.in file, sorted."""
    entries = []
    for root, dirs, files in os.walk(templates_dir):
        dirs.sort()
        for f in sorted(files):
            if f.endswith('.in'):
                abs_path = os.path.join(root, f)
                rel_path = os.path.relpath(abs_path, templates_dir).replace(os.sep, '/')
                entries.append((rel_path, abs_path))
    return sorted(entries)

def escape(content: str) -> str:
    """Wrap content in a C++ raw string literal with a unique delimiter."""
    return 'R"SFTEMPL(\n' + content + '\n)SFTEMPL"'

def build_header(templates_dir: str) -> str:
    """
    Generate a flat header where every template becomes a constexpr string_view.

    Directory structure  templates/uvm/uvm/agent/drv.hpp.in
    becomes the variable  tmpl::uvm::uvm::agent::drv_hpp

    Each unique namespace path is opened exactly once.
    """
    # Collect all entries as (namespace_tuple, var_name, abs_path)
    entries = []
    for rel, abs_path in collect(templates_dir):
        parts = rel.split('/')
        ns_parts = tuple(to_cpp_identifier(p) for p in parts[:-1])
        var_name  = to_cpp_identifier(strip_in(parts[-1]))
        entries.append((ns_parts, var_name, abs_path))

    # Build the namespace tree
    # Each node: { child_key -> node }, values: [(var_name, abs_path)]
    class Node:
        def __init__(self):
            self.children: dict = {}
            self.vars: list     = []

    root = Node()
    for ns_parts, var_name, abs_path in entries:
        node = root
        for part in ns_parts:
            node.children.setdefault(part, Node())
            node = node.children[part]
        node.vars.append((var_name, abs_path))

    lines = [
        "// Auto-generated by embed_templates.py - DO NOT EDIT",
        "// Regenerated at build time whenever a template *.in file changes.",
        "#pragma once",
        "#include <string_view>",
        "",
    ]

    def emit_node(node: Node, ns_stack: list, indent: int):
        pfx = "  " * indent
        # Emit variables at this level
        for var_name, abs_path in node.vars:
            with open(abs_path, 'r', encoding='utf-8') as fh:
                content = fh.read()
            lines.append(f"{pfx}inline constexpr std::string_view {var_name} =")
            lines.append(f"{pfx}  {escape(content)};")
            lines.append("")

        # Recurse into children
        for child_key in sorted(node.children.keys()):
            lines.append(f"{pfx}namespace {child_key} {{")
            emit_node(node.children[child_key], ns_stack + [child_key], indent + 1)
            lines.append(f"{pfx}}} // namespace {child_key}")
            lines.append("")

    lines.append("namespace tmpl {")
    emit_node(root, [], 1)
    lines.append("} // namespace tmpl")

    return "\n".join(lines) + "\n"

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <templates_dir> <output_header>")
        sys.exit(1)

    templates_dir = sys.argv[1]
    output_header = sys.argv[2]

    header = build_header(templates_dir)

    os.makedirs(os.path.dirname(output_header), exist_ok=True)
    with open(output_header, 'w', encoding='utf-8') as fh:
        fh.write(header)

    print(f"[simforge] Generated {output_header} ({header.count(chr(10))} lines)")
