services:
  simforge:
    build:
      context: ..
      dockerfile: toolchain/Dockerfile
    container_name: ${PROJECT_NAME:-simforge}-toolchain
    stdin_open: true
    tty: true
    volumes:
      - ${PROJECT_ROOT:-../../}:/project
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /project
    environment:
      - DISPLAY=${DISPLAY}
